name: Release Pipeline

on:
  workflow_call:
    inputs:
      service_name:
        description: 'Service name (defaults to repository name)'
        required: false
        type: string
        default: ${{ github.event.repository.name }}
      image_tag:
        description: 'Validated image tag to deploy'
        required: true
        type: string
      tenants_repo_name:
        description: 'Tenant repository name'
        required: false
        type: string
        default: ${{ vars.TENANTS_REPO_NAME }}
    secrets:
      BOT_GITHUB_TOKEN:
        description: 'GitHub token for tenant repository access'
        required: true
      AWS_ROLE_ARN:
        description: 'AWS IAM Role ARN for OIDC authentication'
        required: true

env:
  SERVICE_NAME: ${{ inputs.service_name }}
  TENANTS_REPO_NAME: ${{ inputs.tenants_repo_name }}

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Platform Scripts
        uses: actions/checkout@v4
        with:
          repository: arun4infra/zerotouch-platform
          ref: main

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ap-south-1

      - name: Deploy to Dev (Automatic)
        run: ./scripts/release/deploy-direct.sh dev
        env:
          SERVICE_NAME: ${{ env.SERVICE_NAME }}
          IMAGE_TAG: ${{ inputs.image_tag }}
          BOT_GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
          TENANTS_REPO_NAME: ${{ env.TENANTS_REPO_NAME }}

      - name: Force Secret Refresh (Dev)
        run: |
          chmod +x ./scripts/release/force-secret-refresh.sh
          ./scripts/release/force-secret-refresh.sh \
            "${{ inputs.service_name }}" \
            "dev" \
            "platform-identity"

  deploy-staging:
    needs: deploy-dev
    runs-on: ubuntu-latest
    environment: staging
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Platform Scripts
        uses: actions/checkout@v4
        with:
          repository: arun4infra/zerotouch-platform
          ref: main

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ap-south-1

      - name: Deploy to Staging (Manual Approval Required)
        run: ./scripts/release/deploy-direct.sh staging
        env:
          SERVICE_NAME: ${{ env.SERVICE_NAME }}
          IMAGE_TAG: ${{ inputs.image_tag }}
          BOT_GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
          TENANTS_REPO_NAME: ${{ env.TENANTS_REPO_NAME }}

      - name: Force Secret Refresh (Staging)
        run: |
          chmod +x ./scripts/release/force-secret-refresh.sh
          ./scripts/release/force-secret-refresh.sh \
            "${{ inputs.service_name }}" \
            "staging" \
            "platform-identity"

  deploy-production:
    needs: deploy-staging
    runs-on: ubuntu-latest
    environment: production
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Platform Scripts
        uses: actions/checkout@v4
        with:
          repository: arun4infra/zerotouch-platform
          ref: main

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ap-south-1

      - name: Deploy to Production (Manual Approval Required)
        run: ./scripts/release/deploy-direct.sh production
        env:
          SERVICE_NAME: ${{ env.SERVICE_NAME }}
          IMAGE_TAG: ${{ inputs.image_tag }}
          BOT_GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
          TENANTS_REPO_NAME: ${{ env.TENANTS_REPO_NAME }}

      - name: Force Secret Refresh (Production)
        run: |
          chmod +x ./scripts/release/force-secret-refresh.sh
          ./scripts/release/force-secret-refresh.sh \
            "${{ inputs.service_name }}" \
            "prod" \
            "platform-identity"